// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/ini/ini.d.ts
declare module "ini"
{
    interface EncodeOptions {
        section: string
        whitespace: boolean
    }

    function decode(inistring: string): any;

    function parse(initstring: string): any;

    function encode(object: any, options?: EncodeOptions): string;

    function stringify(object: any, options?: EncodeOptions): string;

    function safe(val: string): string;

    function unsafe(val: string): string;

}